cart/urls.py
from django.urls import path

from cart.views import (
    AddProductCartView,
    CartIndexView,
    ClearCartView,
    DeleteProductCartView,
    RestoreOrderPendingCartView,
    UpdateProductCartView,
)

app_name = "cart"

urlpatterns = [
    path("", CartIndexView.as_view(), name="cart"),
    path(
        "add-to-cart/<int:product_id>",
        AddProductCartView.as_view(),
        name="add_product_cart",
    ),
    path(
        "delete-from-cart/<int:product_id>",
        DeleteProductCartView.as_view(),
        name="delete_product_cart",
    ),
    path(
        "update-product-cart/<int:product_id>",
        UpdateProductCartView.as_view(),
        name="update_product_cart",
    ),
    path(
        "restore_cart/<int:order_pending_id>",
        RestoreOrderPendingCartView.as_view(),
        name="restore_order_pending_cart",
    ),
    path("clear-cart/", ClearCartView.as_view(), name="clear_cart"),
]

edshop/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("web.urls")),
    path("account/", include("account.urls")),
    path("cart/", include("cart.urls")),
    path("order/", include("order.urls")),
    path("payment/", include("payment.urls")),
]

web/urls.py
from django.urls import path

from web.views import (
    CatalogView,
    FilterByBrandView,
    FilterByCategoryView,
    LandingView,
    ProductDetailView,
    SearchProductTitleView,
)

app_name = "web"

urlpatterns = [
    path("", LandingView.as_view(), name="landing"),
    path("catalog/", CatalogView.as_view(), name="index"),
    path(
        "by-category/<int:category_id>",
        FilterByCategoryView.as_view(),
        name="filter_by_category",
    ),
    path(
        "by-title/",
        SearchProductTitleView.as_view(),
        name="search_product_title",
    ),
    path(
        "product/<int:product_id>",
        ProductDetailView.as_view(),
        name="product_detail",
    ),
    path(
        "by-brand/<int:brand_id>",
        FilterByBrandView.as_view(),
        name="filter_by_brand",
    ),
]

web/models.py
from cloudinary.models import CloudinaryField
from django.db import models

# Create your models here.


def get_default_brand() -> "Brand":
    brand, _ = Brand.objects.get_or_create(name="None")
    return brand


class Category(models.Model):
    name = models.CharField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-created"]
        verbose_name = "Category"
        verbose_name_plural = "Categories"
        indexes = [
            models.Index(fields=["name"]),
        ]

    def __str__(self) -> str:
        return self.name


class Brand(models.Model):
    name = models.CharField(max_length=50)
    fundator = models.CharField(max_length=100)
    image = CloudinaryField(
        "image",
        blank=True,
        folder="Django-E-commers/media/brands/",
        default="https://res.cloudinary.com/dd1qoripz/image/upload/v1745813449/No_Image_Available_wvog0c.jpg",
        transformation={
            "width": 300,
            "height": 300,
            "crop": "fill",
            "quality": "auto",
            "fetch_format": "auto",
        },
    )
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-created"]
        verbose_name = "Brand"
        verbose_name_plural = "Brands"
        indexes = [
            models.Index(fields=["name", "fundator"]),
        ]

    def __str__(self) -> str:
        return f"{self.name}"


class Product(models.Model):
    title = models.CharField(max_length=200)
    category = models.ForeignKey(Category, on_delete=models.RESTRICT)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    # Optionals
    description = models.TextField(
        blank=True,
        default="No description for this product",
    )
    image = CloudinaryField(
        "image",
        blank=True,
        folder="Django-E-commers/media/products/",
        default="https://res.cloudinary.com/dd1qoripz/image/upload/v1745813449/No_Image_Available_wvog0c.jpg",
        transformation={
            "width": 300,
            "height": 300,
            "crop": "fill",
            "quality": "auto",
            "fetch_format": "auto",
        },
    )
    brand = models.ForeignKey(
        Brand,
        on_delete=models.RESTRICT,
        blank=True,
        default=get_default_brand,
    )
    weight = models.PositiveIntegerField(blank=True, null=True, default=0)
    dimension = models.CharField(max_length=50, blank=True, default="N/A")
    color = models.CharField(max_length=50, blank=True, default="N/A")

    class Meta:
        ordering = ["-created"]
        verbose_name = "Product"
        verbose_name_plural = "Products"
        indexes = [
            models.Index(fields=["title", "category"]),
        ]

    def __str__(self) -> str:
        return f"{self.title} - {self.category} - {self.price}"

templates/web/includes/brands.html
<div class="blog-sb-widget multishopbrands_widget pt-0">
  <h3 class="widgettitle mt-4">Brands</h3>
  <div class="section-sb-current">
    <ul class="section-sb-list">
      {% for brand in brands %}
        <li>
          <a href="{% url 'web:filter_by_brand' brand.id %}">
            <span class="section-sb-label">
              {{ brand.name }}
              <span class="count">{{ brand.product_set.count }}</span>
            </span>
          </a>
        </li>
      {% endfor %}
    </ul>
  </div>
</div>

templates/web/includes/catalog.html
{% load static %}
<script src="{% static 'js/catalogIntersectionObserver.js' %}" defer></script>

<div class="row prod-items prod-items-2 mb-4" id="catalog-section">
  {% for product in products %}
    <form class="cart-actions" action="{% url 'cart:add_product_cart' product.id %}" method="post">
      {% csrf_token %}
      <input type="hidden" name="location-url" value="{{ request.get_full_path }}"/>
      <article class="cf-sm-6 cf-md-6 cf-lg-6 col-xs-6 col-sm-6 col-md-6 col-lg-6 sectgl-item">
        <div class="sectgl prod-i">
          <!-- Product Image -->
          <div class="prod-i-top">
            <a class="prod-i-img" href="{% url 'web:product_detail' product.id %}">
              <img src="
                {% if product.image %}
                  {{ product.image.url }}
                {% else %}
                  https://via.placeholder.com/250
                {% endif %}
                "
                alt="{{ product.title }}"
              />
            </a>
            <div class="prod-i-actions">
              <div class="prod-i-actions-in">
                <p class="prod-i-cart">
                  <button class="hover-label prod-addbtn" type="submit">
                    <i class="icon ion-android-cart"></i>
                    <span>Add to Cart</span>
                  </button>
                  <input type="hidden" name="quantity" value="1">
                </p>
              </div>
            </div>
          </div>
          <div class="prod-i-bot">
            <!-- Product Top -->
            <h3 class="prod-i-ttl">
              <a href="{% url 'web:product_detail' product.id %}">{{ product.title }}</a>
            </h3>
            <!-- Product Bottom -->
            <div class="prod-i-info">
              <p class="prod-i-categ">
                <a href="{% url 'web:filter_by_category' product.category.id %}">{{ product.category }}</a>
              </p>
              <button class="add-to-cart-mobile" type="submit">
                <i class="bi bi-cart-plus"></i>
              </button>
              <p class="prod-i-categ">
                <a href="{% url 'web:filter_by_brand' product.brand.id %}">{{ product.brand }}</a>
              </p>
              <p class="prod-i-price">${{ product.price }}</p>
              <button class="add-to-cart-mobile blue-button" type="submit">
                <i class="bi bi-cart-plus"></i>
              </button>
            </div>
          </div>
        </div>
      </article>
    </form>
  {% endfor %}
</div>

templates/web/includes/categories.html
<div class="blog-sb-widget multishopcategories_widget">
  <h3 class="widgettitle">Categories</h3>
  <div class="section-sb-current">
    <ul class="section-sb-list">
      {% for category in categories %}
        <li>
          <a href="{% url 'web:filter_by_category' category.id %}">
            <span class="section-sb-label">
              {{ category.name }}
              <span class="count">{{ category.product_set.count }}</span>
            </span>
          </a>
        </li>
      {% endfor %}
    </ul>
  </div>
</div>