cart/urls.py
from django.urls import path

from cart.views import (
    AddProductCartView,
    CartIndexView,
    ClearCartView,
    DeleteProductCartView,
    RestoreOrderPendingCartView,
    UpdateProductCartView,
)

app_name = "cart"

urlpatterns = [
    path("", CartIndexView.as_view(), name="cart"),
    path(
        "add-to-cart/<int:product_id>",
        AddProductCartView.as_view(),
        name="add_product_cart",
    ),
    path(
        "delete-from-cart/<int:product_id>",
        DeleteProductCartView.as_view(),
        name="delete_product_cart",
    ),
    path(
        "update-product-cart/<int:product_id>",
        UpdateProductCartView.as_view(),
        name="update_product_cart",
    ),
    path(
        "restore_cart/<int:order_pending_id>",
        RestoreOrderPendingCartView.as_view(),
        name="restore_order_pending_cart",
    ),
    path("clear-cart/", ClearCartView.as_view(), name="clear_cart"),
]

edshop/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("web.urls")),
    path("account/", include("account.urls")),
    path("cart/", include("cart.urls")),
    path("order/", include("order.urls")),
    path("payment/", include("payment.urls")),
]

order/urls.py
from django.urls import path

from order.views import (
    ConfirmOrderView,
    CreateOrderView,
    DeletePendingOrderView,
    OrderSummaryView,
)

app_name = "order"

urlpatterns = [
    path(
        "creating-order/",
        CreateOrderView.as_view(),
        name="create_order",
    ),
    path(
        "confirm-order/",
        ConfirmOrderView.as_view(),
        name="confirm_order",
    ),
    path(
        "delete-pending-order/<int:order_id>",
        DeletePendingOrderView.as_view(),
        name="delete_pending_order",
    ),
    path(
        "order-summary/<int:order_id>",
        OrderSummaryView.as_view(),
        name="order_summary",
    ),
]

web/urls.py
from django.urls import path

from web.views import (
    CatalogView,
    FilterByBrandView,
    FilterByCategoryView,
    LandingView,
    ProductDetailView,
    SearchProductTitleView,
)

app_name = "web"

urlpatterns = [
    path("", LandingView.as_view(), name="landing"),
    path("catalog/", CatalogView.as_view(), name="index"),
    path(
        "by-category/<int:category_id>",
        FilterByCategoryView.as_view(),
        name="filter_by_category",
    ),
    path(
        "by-title/",
        SearchProductTitleView.as_view(),
        name="search_product_title",
    ),
    path(
        "product/<int:product_id>",
        ProductDetailView.as_view(),
        name="product_detail",
    ),
    path(
        "by-brand/<int:brand_id>",
        FilterByBrandView.as_view(),
        name="filter_by_brand",
    ),
]

cart/views.py
import json
from typing import Any

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpRequest, HttpResponseRedirect, JsonResponse
from django.http.response import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.views.generic import TemplateView, View

from cart.cart import Cart
from order.models import Order
from web.models import Product


class CartIndexView(TemplateView):
    template_name = "cart.html"

    def get_context_data(self, **kwargs: dict) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context["pending_orders"] = Order.objects.filter(
            client__user=self.request.user,
            status="0",
        )
        return context

    def get(
        self,
        request: HttpRequest,
        *args: tuple,
        **kwargs: dict,
    ) -> HttpResponse | HttpResponseRedirect:
        cart = Cart(request)

        if not cart.cart:
            messages.info(
                request,
                "Your cart is empty. Please add products to proceed.",
            )
            return redirect(reverse("web:index"))

        return super().get(request, *args, **kwargs)


class AddProductCartView(LoginRequiredMixin, View):
    """View to add products to the cart"""

    http_method_names = ["get", "post"]
    login_url = "/account/login/"

    # Only allow GET for redirect from the login page
    def get(self, request: HttpRequest, **kwargs: dict[str, str]) -> HttpResponse:
        if "product_id" in kwargs and type(kwargs["product_id"]) is int:
            product_id = kwargs["product_id"]
            return self.post(request, product_id)
        return redirect("/")

    def post(
        self,
        request: HttpRequest,
        product_id: int,
    ) -> HttpResponse:
        """Add product with specified quantity and show cart"""

        quantity = int(request.POST.get("quantity", 1))
        product = get_object_or_404(Product, id=product_id)
        cart = Cart(request)
        cart.add(product, quantity)
        messages.success(
            request,
            f'Product "{product.title}" has been added to your cart.',
        )

        actual_location = request.POST.get("location-url")
        if actual_location:
            return redirect(actual_location)

        return redirect("web:index")


class DeleteProductCartView(LoginRequiredMixin, View):
    """View to remove products from the cart"""

    http_method_names = ["post"]
    login_url = "/account/login/"

    @staticmethod
    def post(
        request: HttpRequest,
        product_id: int,
    ) -> HttpResponse:
        cart = Cart(request)
        cart.delete(str(product_id))
        messages.success(request, "Product removed successfully.")

        actual_location = request.POST.get("location-url")
        if actual_location:
            return redirect(actual_location)

        return redirect("/")


class UpdateProductCartView(LoginRequiredMixin, View):
    """View to update a product from the cart"""

    http_method_names = ["patch"]
    login_url = "/account/login/"

    @staticmethod
    def patch(
        request: HttpRequest,
        product_id: int,
    ) -> JsonResponse:
        try:
            data = json.loads(request.body)
            quantity = data.get("quantity")

            # Validate quantity is a positive integer
            if not isinstance(quantity, int) or quantity < 0:
                return JsonResponse(
                    {"error": "Quantity must be a positive integer"},
                    status=400,
                )

            cart = Cart(request)
            cart.update(str(product_id), quantity)

            return JsonResponse(
                {
                    "subtotal": cart.get_order_product_subtotal(str(product_id)),
                    "total_price": cart.get_total_price(),
                    "message": "Product updated successfully",
                },
                status=200,
            )

        except json.JSONDecodeError:
            return JsonResponse({"error": "Invalid JSON"}, status=400)
        except ValueError as error:
            return JsonResponse(
                {"error": f"Invalid quantity: {error!s}"},
                status=400,
            )
        except Exception as error:  # noqa: BLE001
            return JsonResponse({"error": str(error)}, status=400)


class ClearCartView(LoginRequiredMixin, View):
    """View to clear the entire cart"""

    http_method_names = ["post"]
    login_url = "/account/login/"

    @staticmethod
    def post(
        request: HttpRequest,
    ) -> HttpResponse:
        cart = Cart(request)
        cart.clear()

        actual_location = request.POST.get("location-url")
        if actual_location and actual_location != reverse("cart:cart"):
            return redirect(actual_location)

        messages.success(request, "Your cart has been cleared.")
        return redirect("web:index")


class RestoreOrderPendingCartView(LoginRequiredMixin, View):
    """View to restore a pending order to the cart"""

    http_method_names = ["post"]
    login_url = "/account/login/"

    @staticmethod
    def post(
        request: HttpRequest,
        order_pending_id: int,
    ) -> HttpResponse:
        cart = Cart(request)
        cart.restore_order_pending(order_pending_id)
        actual_location = request.POST.get("location-url")

        if actual_location:
            return redirect(actual_location)

        return redirect("/cart/")

templates/base.html
<!DOCTYPE html>
<html lang="en">

  <head>
    {% load static %}
    {% load crispy_forms_tags %}
    <meta charset="UTF-8" />
    <title>Django E-commerce</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="format-detection" content="telephone=no" />

    <meta name="description" content="A comprehensive e-commerce web application built with Django framework featuring modular architecture with dedicated apps for user accounts, shopping cart, order management, and payment processing. The project includes modern development practices with Docker containerization, automated testing, code quality tools (Ruff, pre-commit hooks). ">

    <!-- Facebook Meta Tags -->
    <meta property="og:url" content="https://django-e-commers.onrender.com/">
    <meta property="og:type" content="website">
    <meta property="og:title" content="Django E-commerce">
    <meta property="og:description" content="A comprehensive e-commerce web application built with Django framework featuring modular architecture with dedicated apps for user accounts, shopping cart, order management, and payment processing. The project includes modern development practices with Docker containerization, automated testing, code quality tools (Ruff, pre-commit hooks). ">
    <meta property="og:image" content="https://opengraph.b-cdn.net/production/images/cf05f4e1-d3e0-454e-be8a-4458270d4a4d.jpg?token=cck3XbktDrPCRFpVJbOw2UDMEUdssIWtzG6TDURA6mU&height=1248&width=832&expires=33296912245">

    <!-- Twitter Meta Tags -->
    <meta name="twitter:card" content="summary_large_image">
    <meta property="twitter:domain" content="django-e-commers.onrender.com">
    <meta property="twitter:url" content="https://django-e-commers.onrender.com/">
    <meta name="twitter:title" content="Django E-commerce">
    <meta name="twitter:description" content="A comprehensive e-commerce web application built with Django framework featuring modular architecture with dedicated apps for user accounts, shopping cart, order management, and payment processing. The project includes modern development practices with Docker containerization, automated testing, code quality tools (Ruff, pre-commit hooks). ">
    <meta name="twitter:image" content="https://opengraph.b-cdn.net/production/images/cf05f4e1-d3e0-454e-be8a-4458270d4a4d.jpg?token=cck3XbktDrPCRFpVJbOw2UDMEUdssIWtzG6TDURA6mU&height=1248&width=832&expires=33296912245">

    <!-- Meta Tags Generated via https://www.opengraph.xyz -->

    <link rel="icon" href="{% static 'favicon.ico' %}" type="image/x-icon" />

    <link
      href="https://fonts.googleapis.com/css?family=Montserrat:400,700,900%7COpen+Sans:300,300i,400,400i,600,600i,700,700i&amp;subset=cyrillic"
      rel="stylesheet"
    />

    <!-- IonIcons -->
    <link rel="stylesheet" href="https://unpkg.com/ionicons@2.0.1/css/ionicons.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/ionicons@2.0.1/css/ionicons.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css" />

    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI" crossorigin="anonymous" refer defer></script>

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" />

    <link rel="stylesheet" href="{% static 'css/base.css' %}" />
    <link rel="stylesheet" href="{% static 'css/components/toast.css' %}" />
    <link rel="stylesheet" href="{% static 'css/components/breadcrumbs.css' %}" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <!-- <link rel="stylesheet" href="{% static 'css/media.css' %}" /> -->
    <link rel="stylesheet" href="{% static 'css/layout/header.css' %}" />
    <link rel="stylesheet" href="{% static 'css/layout/footer.css' %}" />
    <!-- jQuery -->
    <script type="text/javascript" src="https://code.jquery.com/jquery-1.12.4.min.js" defer></script>

    <script type="text/javascript" src="{% static 'js/jquery-plugins.js' %}" defer></script>
    <script type="text/javascript" src="{% static 'js/main.js' %}" defer></script>
    <script type="text/javascript" src="{% static 'js/darkmode.js' %}" defer></script>

    {% block head %}
    {% endblock head %}
  </head>

  <body>
    <div id="page" class="site">
      {% include 'includes/top-info.html' %}
      <div class="header-sticky">
        {% include 'includes/header.html' %}
      </div>
      <div id="content" class="site-content">
        <div id="primary" class="content-area">
          <main id="main" class="site-main">
            <div class="cont main-cont">
              {% block content %}
              {% endblock content %}
            </div>
          </main>
        </div>
      </div>
      {% include 'includes/footer.html' %}
    </div>
    {% include 'includes/messages.html' %}
  </body>

</html>

templates/carrito.html
{% extends 'layout.html' %}
{% block content %}
  <h1 class="maincont-ttl">Cart</h1>
  <ul class="b-crumbs">
    <li><a href="/">Home</a></li>
    <li>Cart</li>
  </ul>
  <div class="page-styling">
    <div class="woocommerce prod-litems section-list">
      {% for key,value in request.session.cart.items %}
        <article class="prod-li sectls">
          <div class="prod-li-inner">
            <a href="{% url 'web:product_detail' value.product_id %}" class="prod-li-img">
              <img src="{{ value.image }}" alt="">
            </a>
            <div class="prod-li-cont">
              <div class="prod-li-ttl-wrap">
                <p>
                  <a href="#">{{ value.category }}</a>
                </p>
                <h3><a href="{% url 'web:product_detail' value.product_id %}">{{ value.title }}</a></h3>
              </div>
              <div class="prod-li-prices">
                <div class="prod-li-price-wrap">
                  <p>Price</p>
                  <p class="prod-li-price">${{ value.price }}</p>
                </div>
                <div class="prod-li-qnt-wrap">
                  <p class="qnt-wrap prod-li-qnt">
                    <a href="#" class="qnt-plus prod-li-plus"><i class="icon ion-arrow-up-b"></i></a>
                    <input type="text" value="{{ value.quantity }}">
                    <a href="#" class="qnt-minus prod-li-minus"><i class="icon ion-arrow-down-b"></i></a>
                  </p>
                </div>
                <div class="prod-li-total-wrap">
                  <p>Total</p>
                  <p class="prod-li-total">${{ value.subtotal }}</p>
                </div>
              </div>
            </div>
            <div class="prod-li-info">
              <div class="prod-li-rating-wrap">
                <p data-rating="5" class="prod-li-rating">
                  <i class="rating-ico" title="1"></i>
                  <i class="rating-ico" title="2"></i>
                  <i class="rating-ico" title="3"></i>
                  <i class="rating-ico" title="4"></i>
                  <i class="rating-ico" title="5"></i>
                </p>
                <p class="prod-li-rating-count">12</p>
              </div>
              <p class="prod-li-add">
                <a href="{% url 'web:delete_product_cart' value.product_id %}" class="button hover-label prod-addbtn">
                  <i class="icon ion-close-round"></i><span>Delete</span>
                </a>
              </p>
              <p class="prod-li-information">
                <a href="#" class="hover-label"><i class="icon ion-more"></i><span>Show Information</span></a>
              </p>
            </div>
          </div>
          <div class="page-styling prod-li-informations">
            <dl class="prod-li-props">
              <dt>Brand:</dt>
              <dd><a href="#">{{ value.brand }}</a></dd>
              <dt>Weight:</dt>
              <dd>{{ value.weight }} kg</dd>
              <dt>Dimension:</dt>
              <dd>{{ value.dimension }}</dd>
              <dt>Color:</dt>
              <dd>{{ value.color }}</dd>
            </dl>
          </div>
        </article>
      {% endfor %}
    </div>
    <div class="cart-actions">
      <div class="coupon">
        <input type="text" placeholder="Coupon code">
        <input type="submit" class="button" value="Apply">
      </div>
      <div class="cart-collaterals">
        <a href="{% url 'web:clear_cart' %}" class="checkout-button button">Clear Cart</a>
        <a href="#" class="checkout-button button">Place Order</a>
        <div class="order-total">
          <p class="cart-totals-ttl">Total</p>
          <p class="cart-totals-val">${{ request.session.cart_total_price }}</p>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/cart.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'css/components/forms.css' %}" />
  <link rel="stylesheet" href="{% static 'css/pages/cart.css' %}" />
  <script type="text/javascript" src="{% static 'js/cartPageControl.js' %}" defer></script>
{% endblock head %}

{% block content %}
  <h1 class="main-cont-ttl">Cart</h1>
  <ul class="b-crumbs">
    <li>
      <a href="/">Home</a>
    </li>
    <li>Cart</li>
  </ul>
  <div class="page-styling">
    <div class="woocommerce prod-litems section-list">
      <h2>Your Items</h2>
      {% for product_id, product_order_detail in request.session.cart.items %}
        <article class="prod-li sectls" data-product-id="{{ product_id }}">
          <div class="prod-li-inner">
            <a href="{% url 'web:product_detail' product_id %}" class="prod-li-img"><img src="{{ product_order_detail.image }}" alt="" /></a>
            <div class="cart-item">
              <div class="card-header product-cart">
                <div class="prod-li-ttl-wrap">
                  <a href="{% url 'web:product_detail' product_id %}"><h3>{{ product_order_detail.title }}</h3></a>
                  <p>
                    <a href="{% url 'web:filter_by_category' product_order_detail.category.id %}">{{ product_order_detail.category.name }}</a>
                  </p>
                </div>
                <form class="cart-actions" action="{% url 'cart:delete_product_cart' product_id %}" method="post">
                  {% csrf_token %}
                  <input type="hidden" name="location-url" value="{{ request.get_full_path }}" />
                  <p class="prod-li-add">
                    <button class="button hover-label prod-addbtn" type="submit"><i class="icon ion-close-round"></i></button>
                  </p>
                </form>
              </div>
              <div class="prod-li-info border-0">
                <div class="card-body border-0">
                  <div class="prod-li-prices">
                    <div class="prod-li-price-wrap">
                      <p id="product-price" class="prod-li-price">${{ product_order_detail.price }}</p>
                    </div>
                  </div>
                  <div class="border rounded quantity-control-component">
                    <p class="qnt-wrap prod-li-qnt">
                      <a href="#" class="qnt-minus prod-li-minus border-bottom-0" id="quantity-down"><i class="bi bi-dash"></i></a>
                      <input
                        id="product-quantity"
                        class="mb-0 rounded-0 p-0 text-center h-auto bg-transparent"
                        name="quantity" type="text" value="{{ product_order_detail.quantity }}"
                      />
                      <a href="#" class="qnt-plus prod-li-plus border-bottom-0" id="quantity-up"><i class="bi bi-plus"></i></a>
                    </p>
                  </div>
                  <p class="prod-li-information">
                    <a href="#" class="hover-label">
                      <i class="icon ion-more"></i><span class="show-more-helptext">Show Information</span>
                    </a>
                  </p>
                </div>
              </div>
            </div>
          </div>
          <div class="page-styling prod-li-informations">
            <dl class="prod-li-props">
              <dt>Brand:</dt>
              <dd><a href="{% url 'web:filter_by_brand' product_order_detail.brand.id %}">{{ product_order_detail.brand.name }}</a></dd>
              <dt>Weight:</dt>
              <dd>{{ product_order_detail.weight }} kg</dd>
              <dt>Dimension:</dt>
              <dd>{{ product_order_detail.dimension }}</dd>
              <dt>Color:</dt>
              <dd>{{ product_order_detail.color }}</dd>
            </dl>
          </div>
        </article>
      {% endfor %}
    </div>
    <div class="cart-actions cart-page">
      <div class="coupon">
        <input type="text" id="coupon-code-input" placeholder="Coupon code" />
        <input type="submit" class="button coupon-apply-btn" value="Apply" />
      </div>
      <div class="order-coupon">
        <p class="cart-totals-ttl cart-coupon-ttl">Coupon</p>
        <p class="text-success fw-bold z-1 ps-1 cart-coupon-val">- $ 0.00</p>
      </div>
      <div class="order-total">
        <p class="cart-totals-ttl">Total</p>
        <span class="cart-totals-val">$ {{ request.session.cart_total_price|floatformat:2 }}</span>
      </div>
      <div class="cart-collaterals">
        <form class="cart-actions cart" action="{% url 'cart:clear_cart' %}" method="post">
          {% csrf_token %}
          <input type="hidden" name="location-url" value="{{ request.get_full_path }}" />
          <input class="checkout-button button clear-cart-btn" type="submit" value="Clear Cart" />
        </form>
        <form class="cart-actions cart" action="{% url 'order:create_order' %}" method="get">
          <input class="checkout-button button place-order-btn" type="submit" value="Place Order" />
        </form>
      </div>
    </div>
  </div>
  {% if pending_orders %}
    {% include 'includes/pending-orders.html' %}
  {% endif %}
{% endblock %}

templates/email_validation.html
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Activate Your Account</title>
  </head>

  <body>
    <h1>Here is your activation email</h1>
    <p>Please click the link below to activate your account:</p>
    <a href="{{ activation_link }}">Activate Your Account</a>
  </body>

</html>

templates/gracias.html
{% extends 'layout.html' %}
{% block content %}
<h1 class="maincont-ttl">Checkout OK</h1>
    <ul class="b-crumbs">
        <li><a href="index.html">Home</a></li>
        <li>COMPRA</li>
    </ul>
    <h2>GRACIAS POR TU COMPRA</h2>
{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block head %}
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/media.css' %}" />
{% endblock head %}


{% block content %}
  <div class="section-top">
    <h1 class="main-cont-ttl">Catalog</h1>
    <ul class="b-crumbs">
      <li>
        <a href="{% url 'web:index' %}">Home</a>
      </li>
      <li>Catalog</li>
    </ul>
  </div>
  <!-- To make Sidebar "Not Sticky" just remove id="section-list-withsb" -->
  <div class="section-wrap-withsb">
    <aside class="blog-sb-widgets section-sb" id="section-sb">
      <div class="theiaStickySidebar">
        <p class="section-filter-toggle filter_hidden">
          <a href="#" id="section-filter-toggle-btn">Filters</a>
        </p>
        <div class="section-filter">
          <div class="section-filter">
            {% include 'includes/catalog/categories.html' %}
          </div>
          <div class="section-filter">
            {% include 'includes/catalog/brands.html' %}
          </div>
        </div>
      </div>
    </aside>
    <div class="section-list-withsb" id="section-list-withsb">
      <div class="theiaStickySidebar">
        {% include 'includes/catalog/catalog.html' %}
      </div>
    </div>
  </div>
{% endblock content %}

templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Django E-commers</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="format-detection" content="telephone=no" />

    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,900%7COpen+Sans:300,300i,400,400i,600,600i,700,700i&amp;subset=cyrillic" rel="stylesheet" />

    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/ionicons.min.css' %}" />

    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" />
    <link rel="stylesheet" href="{% static 'css/jquery.formstyler.css' %}" />
    <link rel="stylesheet" href="{% static 'css/flexslider.css' %}" />
    <link rel="stylesheet" href="{% static 'css/jquery.fancybox.css' %}" />
    <link rel="stylesheet" href="{% static 'css/ion.rangeSlider.css' %}" />
    <link rel="stylesheet" href="{% static 'css/jquery.mThumbnailScroller.css' %}" />
    <link rel="stylesheet" href="{% static 'css/chosen.css' %}" />

    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <link rel="stylesheet" href="{% static 'css/elements.css' %}" />
    <link rel="stylesheet" href="{% static 'css/media.css' %}" />
    <link rel="stylesheet" href="{% static 'css/elements-media.css' %}" />
  </head>

  <body>
    <div id="page" class="site">
      {% include 'includes/navbar.html' %} {% include 'includes/header.html' %}
      <div id="content" class="site-content">
        <div id="primary" class="content-area">
          <main id="main" class="site-main">
            <div class="cont maincont">
              {% block content %}{% endblock content %}
            </div>
          </main>
        </div>
      </div>
      {% include 'includes/footer.html' %}
    </div>
    <script src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <script src="{% static 'js/jquery-plugins.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
  </body>
</html>

templates/login.html
{% extends 'base.html' %}

{% comment %}
{% block title %}
  Login/Sig Up
{% endblock %}
{% endcomment %}

{% block content %}
  <h1 class="main-cont-ttl">Registration</h1>
  <ul class="b-crumbs">
    <li>
      <a href="{% url 'web:index' %}">Home</a>
    </li>
    <li>Login</li>
  </ul>

  <article class="page-cont">
    <div class="page-styling">
      <div class="auth-wrap">
        <div class="auth-col">
          <h2>Login</h2>
            {% if messages %}
              <ul class="messages">
                {% for message in messages %}
                  <li class="{{message.tags}}">
                    {{message|safe}}
                    <a href="#" class="close">x</a>
                  </li>
                {% endfor %}
              </ul>
            {% endif %}
          <form method="post" class="login" action="{% url 'account:login_user' %}">
            {% csrf_token %}
            <input type="hidden" name="next" value="{{ destiny }}" />
            <p>
              <label for="username">E-mail <span class="required">*</span></label>
              <input type="email" id="username" name="email" />
            </p>
            <p>
              <label for="password">Password <span class="required">*</span></label>
              <input type="password" id="password" name="password" />
            </p>
            <label for="alert-danger">{{ message }}</label>
            <p class="auth-submit">
              <input type="submit" value="Login" />
              <input type="checkbox" id="rememberme" value="forever" />
              <label for="rememberme">Remember me</label>
            </p>
            <p>
            </p>
            <p class="auth-lost_password">
              <a href="#">Lost your password?</a>
            </p>
          </form>
          <p>
            Don't have an account?
            <a href="{% url 'account:create_user' %}">SignUp</a>
          </p>
        </div>
      </div>
    </div>
  </article>
{% endblock content %}

templates/plantilla.html
{% extends 'layout.html' %}
{% block content %}
{% endblock content %}

templates/thanks.html
{% extends 'base.html' %}
{% block content %}
  <h1 class="main-cont-ttl">Checkout OK</h1>
  <ul class="b-crumbs">
    <li>
      <a href="web/index.html">Home</a>
    </li>
    <li>BUY</li>
  </ul>
  <h2>THANKS FOR YOUR PURCHASE</h2>
{% endblock content %}